#!/usr/bin/env python3
"""Regenerate KINSHIP_2_COMPLETE_PLAN.md from the five planning documents.

Run from the repository root: python3 scripts/docs/build-complete-plan.py
"""
import re

PARTS = [
    ("KINSHIP_2_OPERATIONALIZATION.md", "Part 1 — Operationalization & Build Architecture", "The full plan: tensions, re-audit, domain model, AI, sync, trust, Today, sprig, rollout, architecture, sequence, beta, costs"),
    ("KINSHIP_2_DECISIONS.md", "Part 2 — Founder Decisions", "13 founder decisions, decided by Thor on 1 October 2026"),
    ("KINSHIP_2_EPICS.md", "Part 3 — Epics", "22 epics with acceptance criteria, plus 5 outlined Phase 6 epics"),
    ("KINSHIP_2_TICKETS.md", "Part 4 — Implementation Tickets", "Ordered, independently reviewable tickets with dependencies"),
    ("KINSHIP_2_DELETION_PLAN.md", "Part 5 — Deletion Plan", "What gets deleted from 1.0, and when"),
]


def slug(title):
    s = re.sub(r"[^\w\- ]", "", title.strip().lower())
    return s.replace(" ", "-")


def main():
    titles = {f: t for f, t, _ in PARTS}
    out = [
        "# Kinship 2.0 — Complete Implementation Plan\n",
        "Generated by `scripts/docs/build-complete-plan.py` · Planning documents; founder decisions recorded 1 October 2026\n",
        "This file combines the five Kinship 2.0 planning documents into one. The separate files are the source of truth; regenerate this file after editing them.\n",
        "| Part | Source file | What it holds |\n|---|---|---|",
    ]
    for f, t, d in PARTS:
        out.append(f"| [{t}](#{slug(t)}) | `{f}` | {d} |")
    out.append("")
    for f, t, _ in PARTS:
        lines = open(f).read().split("\n")
        for i, line in enumerate(lines):
            if line.startswith("# "):
                del lines[i]
                break
        body = "\n".join(lines).lstrip("\n")
        body = re.sub(r"^(As of|Recommendations) [^\n]*\n\n?", "", body)
        res, fence = [], False
        for line in body.split("\n"):
            if line.startswith("```"):
                fence = not fence
            if not fence and re.match(r"^#{1,5} ", line):
                line = "#" + line
            res.append(line)
        body = "\n".join(res)
        for g, tt in titles.items():
            if g != f:
                body = body.replace(f"`{g}`", f"[{tt.split(' — ')[0]}](#{slug(tt)})")
        out += ["\n---\n", f"# {t}\n", f"*Source: `{f}`*\n", body.rstrip() + "\n"]
    open("KINSHIP_2_COMPLETE_PLAN.md", "w").write("\n".join(out))


if __name__ == "__main__":
    main()
