/**
 * Garden Walk — Weekly Curated Experience
 *
 * A gentle, scrollable screen focused exclusively on suggested people to tend:
 * 1. A resurfaced memory worth revisiting
 * 2. Up to 3 "plants to tend" — contextually suggested reach-outs
 *
 * Suggestions are generated by the suggestion engine which ranks by:
 * - birthday_upcoming > post_event_capture > drift_reconnect > memory_resurface > general
 * - Persons contacted within the last 24 hours are excluded (INTL-02/03)
 * - Each person shown has a personalized reason (INTL-05, WALK-02)
 *
 * Navigation:
 * - Close (X) -> Home tab
 * - "Reach out" -> /reach-out/[id]
 * - "View memory" -> /person/[id]
 */

import React, { useMemo } from "react";
import { View, Text, Pressable, ScrollView } from "react-native";
import { Stack, router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import Animated, { FadeInUp } from "react-native-reanimated";
import { X, ChevronRight } from "lucide-react-native";
import { colors, fonts, radii, shadows, spacing } from "@design/tokens";
import {
  usePersons,
  useMemories,
  useAllInteractions,
  useSuggestions,
} from "@/hooks";
import type { SuggestionType } from "@/lib/suggestionEngine";

// ─── Suggestion Type Icons ──────────────────────────────────────────────────

const suggestionIcons: Record<SuggestionType, string> = {
  birthday_upcoming: "\ud83c\udf82",
  memory_resurface: "\ud83d\udcad",
  drift_reconnect: "\ud83c\udf3f",
  post_event_capture: "\ud83d\udcf8",
  general_reach_out: "\ud83d\udc8c",
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Get a truncated context reason for a suggestion.
 * For birthday suggestions, extract a short timing line.
 * For all others, use the engine's personalized `reason` field (WALK-02).
 */
function getContextReason(suggestion: { type: SuggestionType; reason: string }): string {
  if (suggestion.type === "birthday_upcoming") {
    // Extract the timing portion from the reason
    // Reason format: "Name's birthday is <timing>. A perfect moment..."
    const match = suggestion.reason.match(/birthday is (.+?)\./);
    const timing = match ? match[1] : "soon";
    return `Birthday ${timing}`;
  }
  // Use the engine's personalized reason, truncated for the UI
  if (suggestion.reason.length > 65) {
    return suggestion.reason.slice(0, 62).trimEnd() + "...";
  }
  return suggestion.reason;
}

function getInitials(name: string): string {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

// ─── Close Handler ──────────────────────────────────────────────────────────

function handleClose() {
  if (router.canGoBack()) {
    router.back();
  } else {
    router.replace("/(tabs)");
  }
}

// ─── Component ──────────────────────────────────────────────────────────────

export default function GardenWalkScreen() {
  const insets = useSafeAreaInsets();

  // ─── Data hooks (all hooks before any early returns) ────────────────────
  const { persons, isLoading: personsLoading } = usePersons();
  const { memories, isLoading: memoriesLoading } = useMemories();
  const { interactions, isLoading: interactionsLoading } =
    useAllInteractions();

  // ─── Generate suggestions (WALK-02: uses contextual intelligence + calendar) ─
  const suggestionsFromEngine = useSuggestions(persons, memories, interactions, 5);

  // Only use suggestions once data is ready
  const allSuggestions = useMemo(() => {
    if (personsLoading || memoriesLoading || interactionsLoading) return [];
    return suggestionsFromEngine;
  }, [suggestionsFromEngine, personsLoading, memoriesLoading, interactionsLoading]);

  // Split: first memory_resurface vs the rest (plants to tend)
  const memoryResurface = useMemo(
    () => allSuggestions.find((s) => s.type === "memory_resurface") ?? null,
    [allSuggestions]
  );

  const plantsToTend = useMemo(
    () =>
      allSuggestions
        .filter((s) => s.type !== "memory_resurface")
        .slice(0, 3),
    [allSuggestions]
  );

  // Find the full memory object for the resurface card
  const resurfacedMemory = useMemo(() => {
    if (!memoryResurface?.metadata?.memoryId) return null;
    return memories.find((m) => m.id === memoryResurface.metadata!.memoryId) ?? null;
  }, [memoryResurface, memories]);

  const isLoading = personsLoading || memoriesLoading || interactionsLoading;
  const isEmpty = !isLoading && allSuggestions.length === 0;

  // ─── Render ─────────────────────────────────────────────────────────────

  return (
    <View style={{ flex: 1, backgroundColor: colors.cream }}>
      <Stack.Screen options={{ headerShown: false }} />

      <ScrollView
        contentContainerStyle={{
          paddingTop: insets.top + spacing.lg,
          paddingBottom: insets.bottom + spacing["3xl"],
          paddingHorizontal: spacing.xl,
        }}
        showsVerticalScrollIndicator={false}
      >
        {/* ─── Close button ─────────────────────────────────────────────── */}
        <Pressable
          onPress={handleClose}
          hitSlop={12}
          style={{
            width: 36,
            height: 36,
            borderRadius: radii.full,
            backgroundColor: colors.white,
            alignItems: "center",
            justifyContent: "center",
            ...shadows.soft,
            marginBottom: spacing.xl,
          }}
        >
          <X size={20} color={colors.warmGray} />
        </Pressable>

        {/* ─── Title ────────────────────────────────────────────────────── */}
        <Animated.View entering={FadeInUp.duration(400)}>
          <Text
            style={{
              fontFamily: fonts.serif,
              fontSize: 28,
              lineHeight: 36,
              color: colors.nearBlack,
              marginBottom: spacing["2xl"],
            }}
          >
            Your garden this week
          </Text>
        </Animated.View>

        {/* ─── Loading state ────────────────────────────────────────────── */}
        {isLoading && (
          <Animated.View entering={FadeInUp.duration(400).delay(100)}>
            <View
              style={{
                backgroundColor: colors.white,
                borderRadius: radii.lg,
                padding: spacing.xl,
                alignItems: "center",
                ...shadows.soft,
              }}
            >
              <Text
                style={{
                  fontFamily: fonts.sans,
                  fontSize: 16,
                  lineHeight: 24,
                  color: colors.warmGray,
                }}
              >
                Gathering your garden...
              </Text>
            </View>
          </Animated.View>
        )}

        {/* ─── Empty state (all tended / no suggestions) ─────────────── */}
        {isEmpty && (
          <Animated.View entering={FadeInUp.duration(400).delay(100)}>
            <View
              style={{
                backgroundColor: colors.white,
                borderRadius: radii.lg,
                padding: spacing.xl,
                alignItems: "center",
                ...shadows.soft,
              }}
            >
              <Text
                style={{
                  fontFamily: fonts.serif,
                  fontSize: 22,
                  lineHeight: 30,
                  color: colors.nearBlack,
                  textAlign: "center",
                  marginBottom: spacing.md,
                }}
              >
                {"\ud83c\udf3f"}
              </Text>
              <Text
                style={{
                  fontFamily: fonts.sans,
                  fontSize: 16,
                  lineHeight: 24,
                  color: colors.nearBlack,
                  textAlign: "center",
                }}
              >
                Your garden is all tended for now.{"\n"}Take a breath and enjoy
                the moment.
              </Text>
            </View>
          </Animated.View>
        )}

        {/* ─── Memory Resurface Card ────────────────────────────────────── */}
        {!isLoading && memoryResurface && resurfacedMemory && (
          <Animated.View
            entering={FadeInUp.duration(400).delay(100)}
            style={{ marginBottom: spacing.xl }}
          >
            <View
              style={{
                backgroundColor: colors.sagePale,
                borderWidth: 1,
                borderColor: colors.sageLight,
                borderRadius: radii.lg,
                padding: spacing.xl,
              }}
            >
              <Text
                style={{
                  fontFamily: fonts.sansSemiBold,
                  fontSize: 14,
                  lineHeight: 20,
                  color: colors.sage,
                  marginBottom: spacing.sm,
                }}
              >
                {suggestionIcons.memory_resurface} A Moment Worth Revisiting
              </Text>

              <Text
                style={{
                  fontFamily: fonts.sans,
                  fontSize: 16,
                  lineHeight: 24,
                  color: colors.nearBlack,
                  marginBottom: spacing.lg,
                }}
                numberOfLines={3}
              >
                {resurfacedMemory.content.length > 60
                  ? resurfacedMemory.content.slice(0, 60).trimEnd() + "..."
                  : resurfacedMemory.content}
              </Text>

              <Pressable
                onPress={() =>
                  router.push(`/person/${memoryResurface.personId}`)
                }
                style={({ pressed }) => ({
                  flexDirection: "row",
                  alignItems: "center",
                  opacity: pressed ? 0.8 : 1,
                })}
              >
                <Text
                  style={{
                    fontFamily: fonts.sansSemiBold,
                    fontSize: 14,
                    lineHeight: 20,
                    color: colors.sage,
                  }}
                >
                  View memory
                </Text>
                <ChevronRight
                  size={16}
                  color={colors.sage}
                  style={{ marginLeft: 2 }}
                />
              </Pressable>
            </View>
          </Animated.View>
        )}

        {/* ─── Plants to Tend ───────────────────────────────────────────── */}
        {!isLoading && plantsToTend.length > 0 && (
          <>
            <Animated.View
              entering={FadeInUp.duration(400).delay(200)}
              style={{ marginBottom: spacing.md }}
            >
              <Text
                style={{
                  fontFamily: fonts.sansSemiBold,
                  fontSize: 16,
                  lineHeight: 24,
                  color: colors.nearBlack,
                }}
              >
                Plants to tend
              </Text>
            </Animated.View>

            <Animated.View
              entering={FadeInUp.duration(400).delay(300)}
              style={{
                backgroundColor: colors.white,
                borderWidth: 1,
                borderColor: colors.border,
                borderRadius: radii.lg,
                overflow: "hidden",
                marginBottom: spacing.xl,
                ...shadows.soft,
              }}
            >
              {plantsToTend.map((suggestion, index) => (
                <View
                  key={suggestion.id}
                  style={{
                    flexDirection: "row",
                    alignItems: "center",
                    paddingHorizontal: spacing.lg,
                    paddingVertical: spacing.md,
                    borderTopWidth: index > 0 ? 1 : 0,
                    borderTopColor: colors.border,
                  }}
                >
                  {/* Avatar */}
                  <View
                    style={{
                      width: 44,
                      height: 44,
                      borderRadius: 22,
                      backgroundColor: colors.sagePale,
                      alignItems: "center",
                      justifyContent: "center",
                      marginRight: spacing.md,
                    }}
                  >
                    <Text
                      style={{
                        fontFamily: fonts.sansSemiBold,
                        fontSize: 14,
                        color: colors.sage,
                      }}
                    >
                      {getInitials(suggestion.personName)}
                    </Text>
                  </View>

                  {/* Name + context */}
                  <View style={{ flex: 1 }}>
                    <Text
                      style={{
                        fontFamily: fonts.sansSemiBold,
                        fontSize: 16,
                        lineHeight: 22,
                        color: colors.nearBlack,
                      }}
                      numberOfLines={1}
                    >
                      {suggestion.personName}
                    </Text>
                    <Text
                      style={{
                        fontFamily: fonts.sans,
                        fontSize: 13,
                        lineHeight: 18,
                        color: colors.warmGray,
                        marginTop: 2,
                      }}
                      numberOfLines={2}
                    >
                      {suggestionIcons[suggestion.type]}{" "}
                      {getContextReason(suggestion)}
                    </Text>
                  </View>

                  {/* Reach out button */}
                  <Pressable
                    onPress={() =>
                      router.push(`/reach-out/${suggestion.personId}`)
                    }
                    style={({ pressed }) => ({
                      flexDirection: "row",
                      alignItems: "center",
                      opacity: pressed ? 0.8 : 1,
                      paddingLeft: spacing.sm,
                    })}
                  >
                    <Text
                      style={{
                        fontFamily: fonts.sansSemiBold,
                        fontSize: 14,
                        lineHeight: 20,
                        color: colors.sage,
                      }}
                    >
                      Reach out
                    </Text>
                    <ChevronRight
                      size={16}
                      color={colors.sage}
                      style={{ marginLeft: 2 }}
                    />
                  </Pressable>
                </View>
              ))}
            </Animated.View>
          </>
        )}

        {/* ─── Closing Text ─────────────────────────────────────────────── */}
        {!isLoading && !isEmpty && (
          <Animated.View
            entering={FadeInUp.duration(400).delay(400)}
            style={{
              alignItems: "center",
              paddingVertical: spacing.xl,
            }}
          >
            <Text
              style={{
                fontFamily: fonts.serif,
                fontSize: 16,
                lineHeight: 24,
                fontStyle: "italic",
                color: colors.sage,
              }}
            >
              Enjoy your week {"\ud83c\udf3f"}
            </Text>
          </Animated.View>
        )}
      </ScrollView>
    </View>
  );
}
